"""Border basis module for quotient algebra representations.

Border bases generalize Gröbner bases to zero-dimensional ideals and provide
numerically stable bases for the quotient algebra K[x]/I. Unlike Gröbner bases,
which depend on a monomial ordering and can be ill-conditioned, border bases
work with any finite K-basis of the quotient space and maintain numerical
stability through orthogonalization.

Key references:
    - Traverso (1990), "A new algorithm for computing in algebraic extensions"
    - Greuel & Pfister (2002), "A Border Basis Algorithm"
    - Becker et al. (2005), "Border Bases and the Moment Problem"

The border basis representation consists of:
    1. A monomial basis B (standard monomials spanning K[x]/I)
    2. The border ∂B = {b·x_i : b in B, i=1..n} \\ B
    3. Multiplication tables: for each f in ∂B, the representation of f mod I
       as a linear combination of elements in B
"""

from itertools import product
from typing import Optional

import numpy as np
from scipy.linalg import null_space

from .symbolic_engine import engine


class BorderBasis:
    """Border basis for the quotient algebra K[x₁,...,xₙ]/I.

    Given an ideal I generated by polynomials g₁,...,gₘ in K[x₁,...,xₙ],
    this class computes a border basis representation of the quotient algebra
    up to a specified degree bound. The border basis provides:

        - A monomial basis B for the quotient space (degree ≤ d)
        - The border ∂B (monomials of degree d+1 reachable from B)
        - Multiplication tables expressing each border element as a linear
          combination of basis elements modulo I

    Args:
        variables: List of symbolic variables [x₁, ..., xₙ].
        generators: List of polynomials generating the ideal I.
        degree: Maximum degree for the monomial basis.

    Attributes:
        nvars: Number of variables.
        degree: Degree bound of the basis.
        basis: List of exponent tuples forming the monomial basis B.
        border: List of exponent tuples forming the border ∂B.
        mult_tables: Dict mapping each border element to its coefficient vector
                     over the basis (i.e., f ≡ Σ c_b · b^α mod I).
    """

    def __init__(self, variables, generators, degree):
        self.variables = list(variables)
        self.nvars = len(variables)
        self.degree = degree
        self.generators = [engine.sympify(g) for g in generators]

        # Compute the border basis via the multiplication table method
        self._compute_basis()
        self._compute_border()
        self._compute_multiplication_tables()

    def _monomial_exponents(self, deg):
        """Generate all exponent tuples of total degree ≤ deg, sorted by degree DESCENDING.

        Sorting descending is critical for the Greuel-Pfister algorithm: pivot columns
        are selected from highest to lowest degree so that higher-degree monomials
        are eliminated first, keeping lower-degree ones in the basis.
        """
        exps = [exp for exp in product(range(deg + 1), repeat=self.nvars)
                if sum(exp) <= deg]
        # Sort by total degree DESCENDING (highest degree first)
        exps.sort(key=lambda e: -sum(e))
        return exps

    def _monomial_from_exp(self, exp):
        """Convert an exponent tuple to a symbolic monomial."""
        result = 1
        for i, e in enumerate(exp):
            if e > 0:
                result *= self.variables[i]**e
        return result

    def _evaluate_poly_at_basis(self, poly, basis_exps):
        """Evaluate a polynomial at each basis monomial's exponent.

        For a polynomial p(x) = Σ c_α x^α and basis element b = x^β,
        this returns the coefficient of x^β in p (i.e., whether β appears in p).

        More precisely, for border basis construction we need to express
        each generator as a linear combination of shifted basis elements.
        """
        poly_dict = engine.Poly(poly, *self.variables).as_dict()
        coeffs = []
        for exp in basis_exps:
            coeffs.append(float(poly_dict.get(exp, 0)))
        return np.array(coeffs)

    def _shifted_evaluations(self, generator, shift_exp):
        """Compute the coefficient vector of x^γ · g mod the monomial basis.

        For a generator g and shift x^γ, compute x^γ·g and extract coefficients
        corresponding to each border element's position in the extended space.
        """
        shifted = self._monomial_from_exp(shift_exp) * generator
        shifted_dict = engine.Poly(shifted, *self.variables).as_dict()
        return shifted_dict

    def _compute_basis(self):
        """Compute the monomial basis B for the quotient algebra A/I.

        The basis consists of all monomials of degree ≤ self.degree that are
        linearly independent modulo the ideal generated by self.generators.

        Algorithm (Greuel-Pfister 2002, border basis via null-space):
          1. Build a relation matrix R whose rows are coefficient vectors of
             x^γ · g_i over all monomials of degree ≤ d **only**.
             CRITICAL: Including degree d+1 columns wastes pivot slots on border
             monomials and prevents correct elimination of dependent basis elements.
          2. Compute the rank-revealing QR decomposition of R^T with column pivoting.
             The first `rank` pivot columns are monomials determined by ideal relations.
          3. Non-pivot columns among degree ≤ d monomials form the standard monomial
             basis B — they cannot be expressed as linear combinations of other columns
             modulo the ideal.

        This is mathematically equivalent to: a monomial x^α is in the basis iff
        its column in R is not a pivot, i.e., it's linearly independent from the
        relation rows spanned by the generators.
        """
        # Monomials up to degree d (for the basis) — ONLY these for R matrix columns
        all_exps_d = self._monomial_exponents(self.degree)

        if not self.generators:
            # No relations — full monomial basis
            self.basis = sorted(all_exps_d, key=lambda e: (-sum(e), e))
            return

        n_basis_cands = len(all_exps_d)
        exp_to_idx = {exp: i for i, exp in enumerate(all_exps_d)}

        # Build relation matrix R from shifted generators.
        # Each row is the coefficient vector of x^gamma * g_i over monomials of degree ≤ d.
        # Columns are indexed by exponent tuples of degree ≤ d ONLY.
        # Shifts γ are chosen so that γ + max(gen_deg) ≤ d, keeping all products in scope.
        constraints = []

        for gen in self.generators:
            gen_dict = engine.Poly(gen, *self.variables).as_dict()
            max_gen_deg = max(sum(exp) for exp in gen_dict.keys())
            max_shift_deg = self.degree - max_gen_deg
            if max_shift_deg < 0:
                # Generator degree exceeds our bound — skip (shouldn't happen for well-formed problems)
                continue

            shift_exps = [e for e in all_exps_d if sum(e) <= max_shift_deg]
            for gamma in shift_exps:
                shifted_dict = self._shifted_evaluations(gen, gamma)
                if not shifted_dict:
                    continue

                # _shifted_evaluations returns x^gamma * g as a poly dict.
                # Only keep terms whose exponents are ≤ d (our column space).
                row = np.zeros(n_basis_cands)
                for shifted_exp, coeff in shifted_dict.items():
                    if sum(shifted_exp) <= self.degree and shifted_exp in exp_to_idx:
                        row[exp_to_idx[shifted_exp]] += float(coeff)

                if np.any(row != 0):
                    constraints.append(row)

        if not constraints:
            self.basis = sorted(all_exps_d, key=lambda e: (-sum(e), e))
            return

        R = np.array(constraints, dtype=float)

        # Degree-aware column scaling before QR.
        # Standard QR column pivoting selects columns by coefficient magnitude,
        # which can incorrectly eliminate low-degree monomials (e.g., the constant
        # term in x^2 - 2 has coefficient -2 > 1). To enforce degree-respecting
        # elimination (higher-degree monomials eliminated first), we scale each
        # column by w^(total_degree) with w > 1. This makes higher-degree columns
        # appear "larger" to the pivoting heuristic, so they are selected as
        # pivot columns and removed from the basis — exactly what border basis
        # theory requires (Greuel-Pfister 2002).
        degree_weights = np.array([10.0 ** sum(exp) for exp in all_exps_d])
        R_scaled = R * degree_weights[np.newaxis, :]

        # Rank estimate via SVD first (needed for tolerance)
        _, S_svd, _ = np.linalg.svd(R_scaled, full_matrices=False)
        tol = 1e-10 * max(R_scaled.shape) * (S_svd[0] if len(S_svd) > 0 else 1.0)
        rank = int(np.sum(S_svd > tol))

        # Rank-revealing QR with column pivoting on the SCALED matrix.
        # scipy.linalg.qr(R, pivoting=True) returns (Q, R_qr, P) such that
        #   R @ perm(P) = Q @ R_qr
        # The first `rank` entries of P are the pivot COLUMNS — monomials whose
        # coefficients are determined by the ideal relations. Non-pivot columns
        # correspond to standard monomials, i.e., the border basis B.
        from scipy.linalg import qr as scipy_qr
        _, _, P = scipy_qr(R_scaled, pivoting=True)
        pivot_cols = set(P[:rank])

        # Standard monomials: those in degree <= d whose column is NOT a pivot
        basis_set = set()
        for exp in all_exps_d:
            idx = exp_to_idx.get(exp)
            if idx is not None and idx not in pivot_cols:
                basis_set.add(exp)

        # Safety: ensure the constant term is always present for zero-dimensional ideals
        zero_exp = (0,) * self.nvars
        if len(basis_set) == 0:
            basis_set = set(all_exps_d)

        self.basis = sorted(basis_set, key=lambda e: (-sum(e), e))

    def _compute_border(self):
        """Compute the border ∂B of the monomial basis.

        The border consists of all monomials x_i · b where b ∈ B and i = 1..n,
        that are NOT in B itself. These are the "boundary" elements that need
        to be expressed as linear combinations of B modulo the ideal.
        """
        basis_set = set(self.basis)
        border_set = set()

        for exp in self.basis:
            for i in range(self.nvars):
                # Multiply by x_i
                new_exp = list(exp)
                new_exp[i] += 1
                new_exp_tuple = tuple(new_exp)

                # Only include if degree is within extended bound and not in basis
                if sum(new_exp_tuple) <= self.degree + 1 and new_exp_tuple not in basis_set:
                    border_set.add(new_exp_tuple)

        self.border = sorted(border_set)

    def _compute_multiplication_tables(self):
        """Compute multiplication tables for the border elements.

        For each border element f ∈ ∂B, find coefficients c_β such that
        f ≡ Σ_{β ∈ B} c_β · x^β  (mod I).

        Algorithm: Direct reduction via generator subtraction.
        For each border monomial x^γ, iteratively subtract scaled generators
        to eliminate leading terms until only basis monomials remain. This is
        equivalent to Groebner-style reduction but uses floating-point arithmetic
        and works with the numerically computed basis from _compute_basis().

        The least-squares approach [V_row | B_mat] @ z ≈ e_f fails when the
        border element lies in Row(R) — the solver can't distinguish ideal
        components from basis components, producing zero coefficients. Direct
        reduction avoids this ambiguity entirely.
        """
        self.mult_tables = {}

        if not self.border or not self.generators:
            return

        n_basis = len(self.basis)
        basis_set = set(self.basis)

        # Pre-compute generator dictionaries for efficient access
        gen_dicts = []
        for gen in self.generators:
            gd = engine.Poly(gen, *self.variables).as_dict()
            # Normalize all exponent keys to plain tuples
            normalized = {tuple(k): v for k, v in gd.items()}
            gen_dicts.append(normalized)

        for border_exp in self.border:
            # Start with the border monomial as a single-term polynomial
            current = {border_exp: 1.0}

            # Iteratively reduce using generators
            max_iterations = 50  # Safety bound against infinite loops
            for _ in range(max_iterations):
                if not current:
                    break

                # Find the "largest" term (highest total degree, then lex)
                leading_exp = max(current.keys(), key=lambda e: (sum(e), e))
                leading_coeff = current[leading_exp]

                # If it's already in the basis, skip to next term
                if leading_exp in basis_set:
                    # Move this term aside and continue reducing others
                    # Actually, we need to reduce ALL non-basis terms
                    # Check if ANY remaining term is not in basis
                    has_non_basis = any(e not in basis_set for e in current)
                    if not has_non_basis:
                        break
                    # Remove this basis term temporarily and continue
                    del current[leading_exp]
                    continue

                # Try to reduce using each generator
                reduced = False
                for gen_dict in gen_dicts:
                    # Find the leading term of this generator
                    gen_leading = max(gen_dict.keys(), key=lambda e: (sum(e), e))
                    gen_leading_coeff = gen_dict[gen_leading]

                    if abs(gen_leading_coeff) < 1e-15:
                        continue

                    # Check if we can cancel the leading term
                    diff_exp = tuple(leading_exp[i] - gen_leading[i] for i in range(self.nvars))

                    # Only use if all components are non-negative (valid monomial division)
                    if any(d < 0 for d in diff_exp):
                        continue

                    # Subtract scaled generator: current -= (leading_coeff / gen_leading_coeff) * x^diff * gen
                    scale = leading_coeff / gen_leading_coeff

                    for g_exp, g_coeff in gen_dict.items():
                        combined = tuple(diff_exp[i] + g_exp[i] for i in range(self.nvars))
                        new_val = current.get(combined, 0.0) - scale * float(g_coeff)
                        if abs(new_val) > 1e-14:
                            current[combined] = new_val
                        elif combined in current:
                            del current[combined]

                    reduced = True
                    break

                if not reduced:
                    # Can't reduce this term further — it's effectively independent
                    # This shouldn't happen for proper border elements, but handle gracefully
                    break

            # Convert remaining terms to coefficient vector indexed by basis position
            coeffs = np.zeros(n_basis)
            for exp, coeff in current.items():
                if exp in basis_set:
                    idx = self.basis.index(exp)
                    coeffs[idx] += coeff

            self.mult_tables[border_exp] = coeffs

    def reduce(self, expr):
        """Reduce an expression using the border basis multiplication tables.

        Args:
            expr: A polynomial expression to reduce modulo the ideal.

        Returns:
            The reduced expression as a linear combination of basis monomials.
        """
        poly = engine.Poly(expr, *self.variables)
        poly_dict = poly.as_dict()

        # Accumulate coefficients for each basis element
        result_coeffs = {exp: 0.0 for exp in self.basis}

        for alpha, coeff in poly_dict.items():
            if alpha in set(self.basis):
                result_coeffs[alpha] += float(coeff)
            else:
                # Reduce higher-degree terms using multiplication tables
                reduced = self._reduce_single_term(alpha, float(coeff))
                for beta, c in reduced.items():
                    result_coeffs[beta] = result_coeffs.get(beta, 0.0) + c

        # Build the reduced symbolic expression
        result = 0
        for exp, coeff in result_coeffs.items():
            if abs(coeff) > 1e-14:
                result += coeff * self._monomial_from_exp(exp)

        return result if result != 0 else 0

    def _reduce_single_term(self, exp, coeff):
        """Reduce a single monomial term x^α · coeff using mult tables.

        Recursively reduces until the exponent is in the basis.
        """
        basis_set = set(self.basis)

        if exp in basis_set:
            return {exp: coeff}

        if sum(exp) > self.degree + 2:
            # Term is too high degree — discard (beyond our representation)
            return {}

        # Try to reduce using multiplication tables
        if exp in self.mult_tables:
            table_coeffs = self.mult_tables[exp]
            result = {}
            for i, c in enumerate(table_coeffs):
                if abs(c) > 1e-14 and i < len(self.basis):
                    beta = self.basis[i]
                    result[beta] = result.get(beta, 0.0) + coeff * c
            return result

        # If not directly in table, try reducing one variable at a time
        for i in range(self.nvars):
            if exp[i] > 0:
                lower_exp = list(exp)
                lower_exp[i] -= 1
                lower_tuple = tuple(lower_exp)

                if lower_tuple in self.mult_tables:
                    # x^exp = x_i · x^lower_exp, reduce x^lower_exp first
                    intermediate = self._reduce_single_term(lower_tuple, coeff)
                    final_result = {}
                    for beta, c in intermediate.items():
                        # Now multiply by x_i and reduce again if needed
                        new_exp = list(beta)
                        new_exp[i] += 1
                        new_tuple = tuple(new_exp)
                        if new_tuple in basis_set:
                            final_result[new_tuple] = final_result.get(new_tuple, 0.0) + c
                        elif new_tuple in self.mult_tables:
                            sub_reduced = {}
                            for j, cj in enumerate(self.mult_tables[new_tuple]):
                                if abs(cj) > 1e-14 and j < len(self.basis):
                                    sub_beta = self.basis[j]
                                    sub_reduced[sub_beta] = (
                                        sub_reduced.get(sub_beta, 0.0) + c * cj
                                    )
                            for beta2, c2 in sub_reduced.items():
                                final_result[beta2] = (
                                    final_result.get(beta2, 0.0) + c2
                                )
                        else:
                            final_result[new_tuple] = final_result.get(new_tuple, 0.0) + c
                    return final_result

        # Cannot reduce further — keep as is
        return {exp: coeff}

    def moment_matrix_structure(self):
        """Return the block structure of the moment matrix induced by the border basis.

        The moment matrix M_α has entries M_{α,β} = y_{α+β} where y are the
        moment variables. The border basis partitions this into blocks based
        on which monomials appear in the basis vs the border.

        Returns:
            dict with keys:
                'basis_size': number of basis elements
                'border_size': number of border elements
                'block_structure': list of (row_start, row_end, col_start, col_end) tuples
        """
        n_basis = len(self.basis)
        n_border = len(self.border)

        return {
            'basis_size': n_basis,
            'border_size': n_border,
            'total_moments': n_basis + n_border,
            'block_structure': [
                (0, n_basis, 0, n_basis),       # Basis × Basis block
                (0, n_basis, n_basis, n_basis + n_border),  # Basis × Border block
                (n_basis, n_basis + n_border, 0, n_basis),  # Border × Basis block
            ]
        }

    def conditioning_diagnostic(self):
        """Compute numerical conditioning diagnostics for the border basis.

        Returns:
            dict with keys:
                'condition_number': condition number of the multiplication table matrix
                'basis_conditioning': condition number of the basis monomial evaluation matrix
                'is_well_conditioned': boolean flag (True if cond < 1e10)
        """
        diagnostics = {}

        # Condition number of multiplication tables
        if self.mult_tables:
            table_matrix = np.array([self.mult_tables[b] for b in self.border])
            if table_matrix.size > 0:
                svs = np.linalg.svd(table_matrix, compute_uv=False)
                cond = float(svs[0] / svs[-1]) if svs[-1] > 1e-15 else float('inf')
                diagnostics['condition_number'] = cond
            else:
                diagnostics['condition_number'] = 1.0
        else:
            diagnostics['condition_number'] = 1.0

        # Basis conditioning via Vandermonde-like evaluation
        if len(self.basis) > 0:
            # Evaluate basis monomials at sample points
            n_samples = min(len(self.basis) * 2, 100)
            np.random.seed(42)
            samples = np.random.uniform(-1, 1, (n_samples, self.nvars))

            vandermonde = np.zeros((n_samples, len(self.basis)))
            for j, exp in enumerate(self.basis):
                for i in range(n_samples):
                    vandermonde[i, j] = np.prod(
                        [samples[i, k]**exp[k] for k in range(self.nvars)]
                    )

            svs = np.linalg.svd(vandermonde, compute_uv=False)
            basis_cond = float(svs[0] / svs[-1]) if svs[-1] > 1e-15 else float('inf')
            diagnostics['basis_conditioning'] = basis_cond
        else:
            diagnostics['basis_conditioning'] = 1.0

        diagnostics['is_well_conditioned'] = (
            diagnostics['condition_number'] < 1e10 and
            diagnostics['basis_conditioning'] < 1e10
        )

        return diagnostics

    def __repr__(self):
        return (
            f"BorderBasis(nvars={self.nvars}, degree={self.degree}, "
            f"basis_size={len(self.basis)}, border_size={len(self.border)})"
        )
